### ISSUE TITLE
C8y Remote Access (prod version)

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io-roadmap#30] opened 2021-12-09 13:04 UTC

**Comment by switschel** [comment] 2022-01-24 15:27
Potential Use Cases:
1. As a device operator / support engineer I need to do a root cause analysis if the information available in Cumulocity is not sufficient. A SSH session is desired via Web SSH to perform those tasks.

2. Advanced use cases are to run diagnostic scripts or get/upload files on the edge devices. Therefor a native SSH/SCP client must be used in combination with a local proxy: https://github.com/SoftwareAG/cumulocity-remote-access-local-proxy

3. Also bridging local HTTP based configuration web pages which could be only exposed via VPN and/or opening any ports externally could be addressed by Remote Access. Using Remote Access you can skip the VPN tunnel and you don't need to open those ports but establish this tunnel via Remote Access (Passthrough).

**Comment by reubenmiller** [comment] 2023-05-10 18:31
Closed. Included as part of thin-edge.io [0.10.0](https://github.com/thin-edge/thin-edge.io/releases/tag/0.10.0)

**Closed as completed by reubenmiller** 2023-05-10 18:31 UTC
Labels: Shipped
